@url = https://stunning-lamp-97665ww4wwq379xw-8080.app.github.dev

GET {{url}}/tarefas

###

GET {{url}}/tarefas/1

###

POST {{url}}/tarefas
Content-Type: application/json

{
    "id": 3,
    "descricao": "Estudar Python"
}

###

PUT {{url}}/tarefas/1
Content-Type: application/json

{
    "descricao": "Estudar C#"
}

###

DELETE {{url}}/tarefas/2